trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo Installing Terraform
    wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    unzip terraform_1.6.6_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
displayName: Install Terraform

- script: |
    cd terraform
    terraform init
    terraform apply -auto-approve
  displayName: Create Infrastructure

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'webapp'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Subscription 1' 
    appName: 'devopswebapp1998'
    package: '$(Build.ArtifactstagingDirectory)/webapp.zip'


